version: '3.8'

services:

  app:
    image: docker.io/library/musl-htmx:v10
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    depends_on:
      - app
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
